const nigeriaCities = [
  {
    state: "Lagos",
    cities: [
      "Agege",
      "Ajeromi-Ifelodun",
      "Alimosho",
      "Amuwo-Odofin",
      "Apapa",
      "Badagry",
      "Epe",
      "Eti-Osa (Ikoyi, Victoria Island, Lekki, Ajah)",
      "Ibeju-Lekki",
      "Ifako-Ijaiye",
      "Ikeja",
      "Ikorodu",
      "Kosofe",
      "Lagos Island (Marina, Obalende, CMS)",
      "Lagos Mainland (Yaba, Ebute-Metta)",
      "Mushin",
      "Ojo (Trade Fair, Okokomaiko)",
      "Oshodi-Isolo",
      "Shomolu",
      "Surulere"
    ]
  },
  {
    state: "Abuja (FCT)",
    cities: [
      "Abaji Town",
      "Agyana",
      "Nuku",
      "Rimba",
      "Alu Mamagi",
      "Yaba (Abaji)",
      "Abaji South",
      "Garki",
      "Wuse",
      "Maitama",
      "Asokoro",
      "Gwarinpa",
      "Utako",
      "Jabi",
      "Central Business District",
      "Apo",
      "Lugbe",
      "Life Camp",
      "Karimu",
      "Nyanya",
      "Karu",
      "Jikwoyi",
      "Orozo",
      "Kurudu",
      "Bwari Town",
      "Kubwa",
      "Dutse",
      "Ushafa",
      "Byazhin",
      "Igu",
      "Shere",
      "Gwagwalada Town",
      "Zuba",
      "Tungan Maje",
      "Dobi",
      "Gwako",
      "Ikwa",
      "Ibwa",
      "Kutunku",
      "Kuje Town",
      "Chibiri",
      "Gaube",
      "Kabi",
      "Rubochi",
      "Kujekwa",
      "Gudunkarya",
      "Kwali Town",
      "Yangoji",
      "Pai",
      "Dafa",
      "Kilankwa",
      "Ashara",
      "Gumbo"
    ]
  }
];


export default nigeriaCities